// User Types
export interface User {
  id: number;
  email: string;
  first_name: string;
  last_name: string;
  created_at: string;
  last_login?: string;
}

export interface UserProfile {
  id: number;
  user_id: number;
  phone?: string;
  notification_preferences: Record<string, boolean>;
  theme_preference: string;
}

// Transaction Types
export interface Transaction {
  id: number;
  user_id?: number;
  amount: number | string;
  date?: string;
  category: string;  // Backend returns category as string, not category_id
  card_actually_used?: number | null;
  card_actually_used_details?: {
    id: number;
    name: string;
    issuer: string;
  } | null;
  recommended_card?: number | null;
  recommended_card_details?: {
    id: number;
    name: string;
    issuer: string;
  } | null;
  actual_reward: number | string;
  optimal_reward: number | string;
  missed_reward: number | string;
  used_optimal_card: boolean;
  merchant: string;
  notes?: string | null;
  created_at: string;
  updated_at?: string;
}

export interface TransactionCategory {
  id: number;
  name: string;
  icon: string;
  color: string;
  description?: string;
}

export interface TransactionFormData {
  amount: number;
  category: string;
  card_actually_used?: number;
  merchant: string;
  notes?: string;
}

// Budget Types
export interface Budget {
  id: number;
  user_id: number;
  category_id: number;
  category?: TransactionCategory;
  amount: number;
  period: string;
  start_date: string;
  end_date: string;
  alert_threshold: number;
  is_active: boolean;
  spent?: number;
  remaining?: number;
  percentage_used?: number;
}

export interface BudgetFormData {
  year_month: string;
  amount: number;
  thresholds: number[];
}

// Credit Card Types (matching backend models)
export interface CreditCard {
  id: number;
  name: string;
  issuer: string; // BANK OF AMERICA, CHASE, AMEX, CITI, CAPITALONE, DISCOVER, USBANK, WELLS FARGO, OTHER
  annual_fee: number;
  ftf: boolean; // Foreign Transaction Fee
  reward_rules?: RewardRule[];
  benefits?: CardBenefit[];
}

export interface CardBenefit {
  id: number;
  card: string; // Card name (read-only from serializer)
  benefits: string[]; // Array of benefit strings
}

export interface UserCard {
  id: number;
  card: number; // card_id
  card_id: number; // Also returned by backend
  card_name?: string; // Generated by backend serializer
  user: number; // user_id (hidden in POST)
  notes?: string; // User's personal notes
  is_active: boolean; // Whether card is active in wallet
}

export interface RewardRule {
  id: number;
  multiplier: number; // Reward multiplier (e.g., 3.0 for 3x)
  category: string | string[]; // Category or categories (can be multi-select)
  cap_amount?: number; // Annual cap in dollars
  notes?: string; // Additional notes about the rule
}

// Category choices from backend
export type RewardCategory =
  | 'SELECTED_CATEGORIES'
  | 'RENT'
  | 'ONLINE_SHOPPING'
  | 'DINING'
  | 'GROCERIES'
  | 'PHARMACY'
  | 'GAS'
  | 'GENERAL_TRAVEL'
  | 'AIRLINE_TRAVEL'
  | 'HOTEL_TRAVEL'
  | 'TRANSIT'
  | 'ENTERTAINMENT'
  | 'OTHER';

export interface CardRecommendation {
  card: CreditCard;
  potential_reward: number;
  reward_type: string;
  reason: string;
}

// Optimizer Types
export interface UserCategorySelection {
  id: number;
  user: number;
  category_tag: RewardCategory;
}

export interface OptimizerResult {
  category_tag: RewardCategory;
  best_card: {
    card_id: number;
    card_name: string;
  } | null;
  multiplier: number;
  rationale: string;
  top3: Array<{
    card_id: number;
    card_name: string;
    multiplier: number;
  }>;
}

export interface CardRecommendationResponse {
  category: string;
  amount?: number;
  recommendation: {
    best_card: {
      card_id: number;
      card_name: string;
    } | null;
    multiplier: number;
    rationale: string;
    top3: Array<{
      card_id: number;
      card_name: string;
      multiplier: number;
    }>;
  };
}

export interface OptimizationStats {
  total_transactions: number;
  optimal_card_usage_count: number;
  optimization_rate: number;
  actual_rewards: number;
  potential_rewards: number;
  missed_rewards: number;
}

// Alert Types
export interface Alert {
  id: number;
  user_id: number;
  alert_type: string;
  title: string;
  message: string;
  priority: string;
  created_at: string;
  is_read: boolean;
  action_url?: string;
}

// Recommendation Types
export interface Recommendation {
  id: number;
  user_id: number;
  recommendation_type: string;
  card_id?: number;
  card?: CreditCard;
  category_id?: number;
  category?: TransactionCategory;
  potential_value: number;
  reason: string;
  created_at: string;
  is_dismissed: boolean;
}

// Analytics Types
export interface SpendingAnalytics {
  period: string;
  total_spent: number;
  total_rewards: number;
  category_breakdown: Array<{
    category: string;
    amount: number;
    percentage: number;
  }>;
  card_usage_stats: Array<{
    card: string;
    transactions: number;
    amount: number;
    rewards: number;
  }>;
}

export interface DashboardData {
  summary: {
    total_spent_this_month: number;
    total_rewards_this_month: number;
    active_budgets: number;
    budget_alerts: number;
  };
  recent_transactions: Transaction[];
  budget_status: Budget[];
  spending_trends: Array<{
    date: string;
    amount: number;
  }>;
  top_cards: UserCard[];
}

// API Response Types
export interface ApiResponse<T> {
  success: boolean;
  data?: T;
  message?: string;
  error?: {
    code: string;
    message: string;
    details?: Record<string, string[]>;
  };
}

// Auth Types
export interface LoginCredentials {
  email: string;
  password: string;
}

export interface RegisterData {
  email: string;
  password: string;
  first_name: string;
  last_name: string;
}

export interface AuthResponse {
  token: string;
  user: User;
}

