# Generated by Django 5.2.8 on 2025-11-07 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0017_alter_cardbenefit_benefits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount ($)')),
                ('category', models.CharField(choices=[('SELECTED_CATEGORIES', 'Selected Categories'), ('RENT', 'Rent'), ('ONLINE_SHOPPING', 'Online Shopping'), ('DINING', 'Dining'), ('GROCERIES', 'Groceries'), ('PHARMACY', 'Pharmacy'), ('GAS', 'Gas'), ('GENERAL_TRAVEL', 'General Travel'), ('AIRLINE_TRAVEL', 'Airline Travel'), ('HOTEL_TRAVEL', 'Hotel Travel'), ('TRANSIT', 'Transit'), ('ENTERTAINMENT', 'Entertainment'), ('OTHER', 'Other')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='cards.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
