# Generated by Django 5.2.7 on 2025-10-24 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCategorySelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_tag', models.CharField(choices=[('SELECTED_CATEGORIES', 'Selected Categories'), ('RENT', 'Rent'), ('ONLINE_SHOPPING', 'Online Shopping'), ('DINING', 'Dining'), ('GROCERIES', 'Groceries'), ('PHARMACY', 'Pharmacy'), ('GAS', 'Gas'), ('GENERAL_TRAVEL', 'General Travel'), ('AIRLINE_TRAVEL', 'Airline Travel'), ('HOTEL_TRAVEL', 'Hotel Travel'), ('TRANSIT', 'Transit'), ('ENTERTAINMENT', 'Entertainment'), ('OTHER', 'Other')], max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimizer_selections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='optimizer_u_user_id_5f6de0_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'category_tag'), name='uniq_user_category_selection')],
            },
        ),
    ]
