# Generated by Django 5.2.7 on 2025-10-20 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('issuer', models.CharField(max_length=255)),
                ('annual_fee', models.DecimalField(decimal_places=0, max_digits=3)),
                ('ftf', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RewardRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('multiplier', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('cashback_percent', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('cap_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_rules', to='cards.card')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('card', 'category'), name='unique_card_category')],
            },
        ),
    ]
