# Generated by Django 5.2.7 on 2025-10-20 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='card',
            name='notes',
        ),
        migrations.AlterField(
            model_name='card',
            name='annual_fee',
            field=models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Annual Fee ($)'),
        ),
        migrations.AlterField(
            model_name='card',
            name='ftf',
            field=models.BooleanField(default=True, verbose_name='Foreign Transaction Fee'),
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cards', to='cards.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'card'), name='uniq_user_card')],
            },
        ),
    ]
