# Generated by Django 5.2.7 on 2025-10-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_remove_card_is_active_remove_card_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='issuer',
            field=models.CharField(choices=[('BANK OF AMERICA', 'Bank of America'), ('CHASE', 'Chase'), ('AMEX', 'American Express'), ('CITI', 'Citi'), ('CAPITALONE', 'Capital One'), ('DISCOVER', 'Discover'), ('USBANK', 'US Bank'), ('WELLS FARGO', 'Wells Fargo'), ('OTHER', 'Other')], max_length=255),
        ),
    ]
