# Generated by Django 5.2.7 on 2025-10-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_card_issuer'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='coupon_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Coupon Value ($)'),
        ),
        migrations.AddField(
            model_name='card',
            name='coupon_description',
            field=models.TextField(blank=True, null=True, verbose_name='Coupon Description'),
        ),
        migrations.AddField(
            model_name='card',
            name='coupon_frequency',
            field=models.CharField(blank=True, choices=[('ONCE', 'One-time'), ('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual')], max_length=20, null=True, verbose_name='Coupon Frequency'),
        ),
        migrations.AddField(
            model_name='card',
            name='coupon_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Coupon Name'),
        ),
    ]
