# Generated by Django 5.2.7 on 2025-10-21 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_rewardrule_notes_alter_rewardrule_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='coupon_frequency',
            field=models.CharField(blank=True, choices=[('ONCE', 'One-time'), ('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual'), ('EVERY_4_5_YEARS', 'Every 4/5 Years')], max_length=20, null=True, verbose_name='Coupon Frequency'),
        ),
    ]
