# Generated by Django 5.2.7 on 2025-10-21 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_card_coupon_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='coupon_amount',
        ),
        migrations.RemoveField(
            model_name='card',
            name='coupon_description',
        ),
        migrations.RemoveField(
            model_name='card',
            name='coupon_frequency',
        ),
        migrations.RemoveField(
            model_name='card',
            name='coupon_name',
        ),
        migrations.CreateModel(
            name='CardBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('frequency', models.CharField(blank=True, choices=[('ONCE', 'One-time'), ('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual'), ('EVERY_4_5_YEARS', 'Every 4/5 Years')], max_length=20, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='cards.card')),
            ],
        ),
    ]
