# Generated by Django 5.2.7 on 2025-10-21 03:13

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_remove_card_coupon_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewardrule',
            name='cashback_percent',
        ),
        migrations.AddField(
            model_name='cardbenefit',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('DINING', 'Dining'), ('GROCERIES', 'Groceries'), ('TRAVEL', 'Travel'), ('ENTERTAINMENT', 'Entertainment'), ('OTHER', 'Other')], default='GENERAL', max_length=255),
        ),
        migrations.AlterField(
            model_name='cardbenefit',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cardbenefit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardbenefit',
            name='frequency',
            field=models.CharField(choices=[('ONCE', 'One-time'), ('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual'), ('EVERY_4_5_YEARS', 'Every 4/5 Years')], default='ONCE'),
        ),
        migrations.AlterField(
            model_name='rewardrule',
            name='cap_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Cap Amount (annual $)'),
        ),
        migrations.AlterField(
            model_name='rewardrule',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SELECTED_CATEGORIES', 'Selected Categories'), ('RENT', 'Rent'), ('ONLINE_SHOPPING', 'Online Shopping'), ('DINING', 'Dining'), ('GROCERIES', 'Groceries'), ('GAS', 'Gas'), ('GENERAL_TRAVEL', 'General Travel'), ('AIRLINE_TRAVEL', 'Airline Travel'), ('HOTEL_TRAVEL', 'Hotel Travel'), ('TRANSIT', 'Transit'), ('ENTERTAINMENT', 'Entertainment'), ('OTHER', 'Other')], help_text='Select one or more categories that share this multiplier (hold Ctrl or Cmd to select multiple).', max_length=255, verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='rewardrule',
            name='multiplier',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Multiplier (x or %)'),
        ),
    ]
