# Generated by Django 5.2.7 on 2025-10-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_remove_rewardrule_cashback_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardbenefit',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=None, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cardbenefit',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('DINING', 'Dining'), ('GROCERIES', 'Groceries'), ('TRAVEL', 'Travel'), ('ENTERTAINMENT', 'Entertainment'), ('OTHER', 'Other')], default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='cardbenefit',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cardbenefit',
            name='frequency',
            field=models.CharField(choices=[('ONCE', 'One-time'), ('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual'), ('EVERY_4_5_YEARS', 'Every 4/5 Years')], default=None),
        ),
        migrations.AlterField(
            model_name='rewardrule',
            name='multiplier',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=5, verbose_name='Multiplier (x or %)'),
        ),
    ]
