# Generated by Django 5.2.7 on 2025-10-21 03:25

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_alter_cardbenefit_amount_alter_cardbenefit_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardrule',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SELECTED_CATEGORIES', 'Selected Categories'), ('RENT', 'Rent'), ('ONLINE_SHOPPING', 'Online Shopping'), ('DINING', 'Dining'), ('GROCERIES', 'Groceries'), ('GAS', 'Gas'), ('GENERAL_TRAVEL', 'General Travel'), ('AIRLINE_TRAVEL', 'Airline Travel'), ('HOTEL_TRAVEL', 'Hotel Travel'), ('TRANSIT', 'Transit'), ('ENTERTAINMENT', 'Entertainment'), ('OTHER', 'Other')], max_length=255, verbose_name='Categories'),
        ),
    ]
