# Generated by Django 5.2.7 on 2025-10-21 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_alter_rewardrule_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardrule',
            name='cap_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True, verbose_name='Cap Amount (annual $)'),
        ),
    ]
