# Generated by Django 5.2.7 on 2025-10-21 06:16

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_alter_rewardrule_cap_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardbenefit',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='rewardrule',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SELECTED_CATEGORIES', 'Selected Categories'), ('RENT', 'Rent'), ('ONLINE_SHOPPING', 'Online Shopping'), ('DINING', 'Dining'), ('GROCERIES', 'Groceries'), ('PHARMACY', 'Pharmacy'), ('GAS', 'Gas'), ('GENERAL_TRAVEL', 'General Travel'), ('AIRLINE_TRAVEL', 'Airline Travel'), ('HOTEL_TRAVEL', 'Hotel Travel'), ('TRANSIT', 'Transit'), ('ENTERTAINMENT', 'Entertainment'), ('OTHER', 'Other')], max_length=255, verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='rewardrule',
            name='multiplier',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, verbose_name='Multiplier (x or %)'),
        ),
    ]
