# Generated by Django 5.2.7 on 2025-10-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_alter_cardbenefit_amount_alter_rewardrule_category_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rewardrule',
            name='unique_card_category',
        ),
        migrations.AlterField(
            model_name='card',
            name='annual_fee',
            field=models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Annual Fee ($)'),
        ),
        migrations.AlterField(
            model_name='cardbenefit',
            name='frequency',
            field=models.CharField(choices=[('ONCE', 'One-time'), ('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual'), ('EVERY_4_5_YEARS', 'Every 4/5 Years')], default=None, max_length=20),
        ),
    ]
