# Generated by Django 5.2.7 on 2025-10-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_remove_rewardrule_unique_card_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardbenefit',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='cardbenefit',
            name='category',
        ),
        migrations.RemoveField(
            model_name='cardbenefit',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cardbenefit',
            name='frequency',
        ),
        migrations.AddField(
            model_name='cardbenefit',
            name='benefits',
            field=models.JSONField(blank=True, default=list, help_text='List of card benefits'),
        ),
    ]
