# Generated by Django 5.2.7 on 2025-10-23 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0014_remove_cardbenefit_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardbenefit',
            name='name',
        ),
    ]
