# Generated by Django 5.2.7 on 2025-10-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0015_remove_cardbenefit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardbenefit',
            name='benefits',
            field=models.TextField(blank=True, null=True),
        ),
    ]
