# Generated by Django 5.2.7 on 2025-10-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0016_alter_cardbenefit_benefits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardbenefit',
            name='benefits',
            field=models.TextField(blank=True, null=True, verbose_name='Benefits'),
        ),
    ]
